const PDFDocument = require("pdfkit");

module.exports = function generateDealerPDF(res, dealer) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=Dealer_${dealer.id}.pdf`
  );

  doc.pipe(res);

  // ===== HEADER =====
  doc
    .fontSize(20)
    .text("AutoKart – Dealer Application Details", { align: "center" })
    .moveDown(2);

  // ===== DETAILS =====
  doc.fontSize(12);

  const field = (label, value) => {
    doc
      .font("Helvetica-Bold")
      .text(label + ": ", { continued: true })
      .font("Helvetica")
      .text(value || "-")
      .moveDown(0.5);
  };

  field("Dealer ID", dealer.id);
  field("Full Name", dealer.full_name);
  field("Mobile", dealer.mobile);
  field("Email", dealer.email);
  field("City", dealer.city);
  field("Dealer Type", dealer.dealer_type);
  field("Status", dealer.status.toUpperCase());
  field("Applied On", new Date(dealer.created_at).toDateString());

  if (dealer.status === "rejected") {
    field("Rejection Reason", dealer.rejection_reason || "N/A");
  }

  doc.moveDown(2);
  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by AutoKart Admin Panel", {
      align: "center"
    });

  doc.end();
};
